/**
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package EOS;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
//@WebServiceClient(name = "EosService", targetNamespace = "http://tempuri.org/", wsdlLocation = "http://eos.sb.karmalab.net:8000/eosservice?wsdl")
@WebServiceClient(name = "EosService", targetNamespace = "http://tempuri.org/")
public class EosService
    extends Service
{

    private final static URL EOSSERVICE_WSDL_LOCATION;
    private final static WebServiceException EOSSERVICE_EXCEPTION;
    private final static QName EOSSERVICE_QNAME = new QName("http://tempuri.org/", "EosService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://eos.sb.karmalab.net:8000/eosservice?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        EOSSERVICE_WSDL_LOCATION = url;
        EOSSERVICE_EXCEPTION = e;
    }

    public EosService() {
        super(__getWsdlLocation(), EOSSERVICE_QNAME);
    }

    //public EosService(WebServiceFeature... features) {
    //    super(__getWsdlLocation(), EOSSERVICE_QNAME, features);
    //}

    public EosService(URL wsdlLocation) {
        super(wsdlLocation, EOSSERVICE_QNAME);
    }

    //public EosService(URL wsdlLocation, WebServiceFeature... features) {
    //    super(wsdlLocation, EOSSERVICE_QNAME, features);
    //}

    public EosService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    //public EosService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
    //    super(wsdlLocation, serviceName, features);
    //}

    /**
     * 
     * @return
     *     returns IEosService
     */
    @WebEndpoint(name = "WSHttpBinding_IEosService")
    public IEosService getWSHttpBindingIEosService() {
        return super.getPort(new QName("http://tempuri.org/", "WSHttpBinding_IEosService"), IEosService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IEosService
     */
    @WebEndpoint(name = "WSHttpBinding_IEosService")
    public IEosService getWSHttpBindingIEosService(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "WSHttpBinding_IEosService"), IEosService.class, features);
    }

    /**
     * 
     * @return
     *     returns IEosService
     */
    @WebEndpoint(name = "BasicHttpBinding_IEosService")
    public IEosService getBasicHttpBindingIEosService() {
        return super.getPort(new QName("http://tempuri.org/", "BasicHttpBinding_IEosService"), IEosService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IEosService
     */
    @WebEndpoint(name = "BasicHttpBinding_IEosService")
    public IEosService getBasicHttpBindingIEosService(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "BasicHttpBinding_IEosService"), IEosService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (EOSSERVICE_EXCEPTION!= null) {
            throw EOSSERVICE_EXCEPTION;
        }
        return EOSSERVICE_WSDL_LOCATION;
    }

}
