/**
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package EOS;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IEosService", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IEosService {




    /**
     * 
     * @param details
     * @param failureKey
     * @param hostname
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "NotifyNodeFailure", action = "http://tempuri.org/IEosService/NotifyNodeFailure")
    @WebResult(name = "NotifyNodeFailureResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "NotifyNodeFailure", targetNamespace = "http://tempuri.org/", className = "EOS.NotifyNodeFailure")
    @ResponseWrapper(localName = "NotifyNodeFailureResponse", targetNamespace = "http://tempuri.org/", className = "EOS.NotifyNodeFailureResponse")
    @Action(input = "http://tempuri.org/IEosService/NotifyNodeFailure", output = "http://tempuri.org/IEosService/NotifyNodeFailureResponse")
    public Boolean notifyNodeFailure(
        @WebParam(name = "hostname", targetNamespace = "http://tempuri.org/")
        String hostname,
        @WebParam(name = "failureKey", targetNamespace = "http://tempuri.org/")
        String failureKey,
        @WebParam(name = "details", targetNamespace = "http://tempuri.org/")
        String details);



}
